# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_win_accounting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 280, 321, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_txt_profit = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_txt_profit.setObjectName("lbl_txt_profit")
        self.horizontalLayout.addWidget(self.lbl_txt_profit)
        self.lbl_profit_number = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_profit_number.setObjectName("lbl_profit_number")
        self.horizontalLayout.addWidget(self.lbl_profit_number)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(70, 100, 321, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_txt_cost = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lbl_txt_cost.setObjectName("lbl_txt_cost")
        self.horizontalLayout_2.addWidget(self.lbl_txt_cost)
        self.lbl_cost_number = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lbl_cost_number.setObjectName("lbl_cost_number")
        self.horizontalLayout_2.addWidget(self.lbl_cost_number)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(70, 180, 321, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_txt_income = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.lbl_txt_income.setObjectName("lbl_txt_income")
        self.horizontalLayout_3.addWidget(self.lbl_txt_income)
        self.lbl_income_number = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.lbl_income_number.setObjectName("lbl_income_number")
        self.horizontalLayout_3.addWidget(self.lbl_income_number)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 331, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Accounting"))
        self.lbl_txt_profit.setText(_translate("Form", "Profit:"))
        self.lbl_profit_number.setText(_translate("Form", "0"))
        self.lbl_txt_cost.setText(_translate("Form", "Cost:"))
        self.lbl_cost_number.setText(_translate("Form", "0"))
        self.lbl_txt_income.setText(_translate("Form", "Income:"))
        self.lbl_income_number.setText(_translate("Form", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Overview"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cost"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Income"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Profit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Cost && Income"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
